### ISSUE TITLE
DFD Comments - Sept 20

### ISSUE THREAD

**Issue by germonprez** [jhperz/3420ISQAAssignment1#10]
Some comments on your DFD: 

1) Something should happen to License Details. Right now they are stopping at the Software License Scanner process. They are not serving a purpose. 

2) The Manager should also be asking for the software package information (in addition to the license data request).

**Comment by Jeebbuuss** [comment]
Here is the updated DFD designed to address these issues.

![dfd 9-28-16](https://cloud.githubusercontent.com/assets/9424384/18939641/455a5788-85c7-11e6-9e27-fee267cfb175.jpeg)
